[package]
name = "calendarchy-core"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
tokio.workspace = true
rusqlite.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
oo7 = { version = "0.6.0", features = ["tokio", "native_crypto"] }
oauth2 = "5.0.0"
